# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_receiptcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptintegrientrelation',
            name='amount_type',
            field=models.CharField(choices=[(b'K', b'Kilogramm'), (b'G', b'Gramm'), (b'L', b'Liter'), (b'M', b'Milliliter'), (b'T', b'TL'), (b'E', b'EL'), (b'S', b'St\xc3\xbcck'), (b'B', b'Becher'), (b'P', b'Prise(n)'), (b'C', b'P\xc3\xa4ckchen'), (b'F', b'Flasche(n)'), (b'N', b'Scheibe(n)'), (b'W', b'Etwas')], max_length=1),
        ),
    ]
