# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20151203_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcategory',
            name='is_country',
            field=models.NullBooleanField(default=False),
        ),
    ]
