# Generated by Django 3.1.3 on 2020-11-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20201118_0954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceiptCategoryRelation',
            new_name='RecipeCategoryRelation',
        ),
        migrations.RenameModel(
            old_name='ReceiptIngredientRelation',
            new_name='RecipeIngredientRelation',
        ),
        migrations.RenameModel(
            old_name='ReceiptTopic',
            new_name='RecipeTopic',
        ),
        migrations.RenameModel(
            old_name='ReceiptTopicRelation',
            new_name='RecipeTopicRelation',
        ),
        migrations.AlterModelOptions(
            name='recipecategoryrelation',
            options={'ordering': ['recipe__name']},
        ),
        migrations.RenameField(
            model_name='recipecategoryrelation',
            old_name='receipt',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipecategoryrelation',
            old_name='receiptCategory',
            new_name='recipeCategory',
        ),
        migrations.RenameField(
            model_name='recipetopic',
            old_name='parentReceiptTopic',
            new_name='parentRecipeTopic',
        ),
        migrations.RenameField(
            model_name='recipetopicrelation',
            old_name='receipt',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipetopicrelation',
            old_name='receiptTopic',
            new_name='recipeTopic',
        ),
    ]
