# Generated by Django 3.1.3 on 2020-11-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_recipe_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecategoryrelation',
            name='is_main',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
