# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20151128_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'media/category'),
        ),
    ]
