# Generated by Django 3.1.3 on 2020-11-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20201118_0941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipt',
            new_name='Recipe',
        ),
        migrations.RenameModel(
            old_name='ReceiptCategory',
            new_name='RecipeCategory',
        ),
        migrations.RenameField(
            model_name='receiptingredientrelation',
            old_name='receipt',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipecategory',
            old_name='parentReceiptCategory',
            new_name='parentRecipeCategory',
        ),
    ]
