# Generated by Django 3.1.3 on 2020-11-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_recipebookreciperelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
